### PR TITLE
Added macro for passing all arguments of a method as implicit parameter

### PR DESCRIPTION
**Pull request by benhag**

### CODE REVIEW

**Comment by fizzy33** [comment]
Looks cool...  Might want to add another assert in the unit test

assert(args.value(1).size == 2

**Comment by lihaoyi** [comment]
Fascinating.

Any chance you could get it working scala-2.10? You probably just need to swap out `paramLists` for `paramss` or something similar.

I also would like a test case that includes a constructor as the nearest-enclosing-method, just to make sure it behaves in that scenario

**Comment by lihaoyi** [comment]
Only slightly related, but it would be cool to have an implicit for "everything in scope" rather than just the nearest-enclosing-method's parameters. It would be huge, and we would have to synthesize fake objects to get around the silly `package foo is not a value` problems, but it would be useful for similar reasons a the current PR

**Comment by benhag** [comment]
Already trying to get it working in scala-2.10.

**Comment by benhag** [comment]
I've fixed the 2.10 compatibility, but it's currently not working with a constructor as nearest enclosing method. Still working on this...

**Comment by benhag** [comment]
I'm probably just missing something, but I haven't found a way to access the constructor parameter with Scala 2.10.
Here is what I've done:
- With 2.11 it is working as expected, for a constructor as well as for a method
- With 2.10 it is working for method or alternate constructors. Within the primary constructor `Args.value` will be an empty list. So at least one wont get any compiler errors :-(

**Comment by benhag** [comment]
I'm not sure that it's a good idea to pass an empty list if `Args` is used within a primary constructor in 2.10. It might be better to abort the build with a clear compiler error - as long as nobody has an idea how to access the constructor arguments.

**Comment by benhag** [comment]
Ok, found a way to access the constructor parameters in 2.10.

**Comment by lihaoyi** [comment]
Looks good, thanks!

**Pull request merged**
